CREATE TABLE CLIENTS (
    ID_CLIENT VARCHAR2(10) PRIMARY KEY,
    NOM VARCHAR2(50) NOT NULL,
    PRENOM VARCHAR2(50),
    RAISON_SOCIALE VARCHAR2(100),
    EMAIL VARCHAR2(100) UNIQUE,
    TELEPHONE VARCHAR2(15),
    DATE_CREATION VARCHAR2(20)
);