CREATE TABLE COMPTES (
    ID_COMPTE VARCHAR2(11) PRIMARY KEY,
    ID_CLIENT VARCHAR2(10) NOT NULL,
    NUMERO_COMPTE VARCHAR2(27) UNIQUE NOT NULL,
    SOLDE NUMBER(10,2) DEFAULT 0,
    TYPE_COMPTE VARCHAR2(20) CHECK (TYPE_COMPTE IN ('COURANT', 'EPARGNE', 'PROFESSIONNEL')),
    DATE_OUVERTURE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_COMPTES_CLIENTS FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTS(ID_CLIENT)
);