CREATE TABLE MOUVEMENTS (
    ID_MOUVEMENT VARCHAR2(20) PRIMARY KEY,
    ID_COMPTE VARCHAR2(11) NOT NULL,
    DATE_MOUVEMENT DATE DEFAULT SYSDATE,
    MONTANT NUMBER(10,2) NOT NULL,
    TYPE_MOUVEMENT VARCHAR2(20) CHECK (TYPE_MOUVEMENT IN ('CREDIT', 'DEBIT')),
    CONSTRAINT FK_MOUVEMENTS_COMPTES FOREIGN KEY (ID_COMPTE) REFERENCES COMPTES(ID_COMPTE)
);