CREATE TABLE TR_RETALL (
  DATE_EXTRACT           VARCHAR2(10 BYTE),
  PERIODDEC              VARCHAR2(6 BYTE),
  AGENCE                 VARCHAR2(3 CHAR),
  TYPEIDENTIFIANT        VARCHAR2(1 BYTE),
  CODEIDENTIFIANT        CHAR(20 CHAR),
  NOM                    CHAR(36 CHAR),
  PRENOM                 VARCHAR2(36 CHAR),
  CATEGBENIF             VARCHAR2(1 BYTE),
  AGE                    NUMBER,
  NATIONALITE            VARCHAR2(40 CHAR),
  NATOP                  VARCHAR2(4 BYTE),
  CADRETRO               VARCHAR2(1 BYTE),
  DATRETRO               DATE,
  MNTRETRODEV            NUMBER(19,4),
  DEVMNTRETRO            CHAR(3 CHAR),
  CVMNTRETRO             NUMBER(19,4),
  NUMAUTBCTSD            VARCHAR2(40 BYTE),
  DATAUTBCTSD            DATE,
  DATRETVOY              DATE,
  NUMDECD                VARCHAR2(10 BYTE),
  DATDECD                DATE,
  DATDELIVALLOCTOURIS    DATE,
  AGE1                   CHAR(5 CHAR),
  CLI                    CHAR(15 CHAR),
  OPE                    CHAR(3 CHAR),
  EVE                    CHAR(6 CHAR)
);