--exemple insertion
INSERT INTO CLIENTS (ID_CLIENT, NOM, PRENOM, RAISON_SOCIALE, EMAIL, TELEPHONE, DATE_CREATION) 
VALUES (1, 'Dupont', 'Jean', NULL, 'jean.dupont@email.com', '0612345678', SYSDATE);

INSERT INTO CLIENTS (ID_CLIENT, NOM, PRENOM, RAISON_SOCIALE, EMAIL, TELEPHONE, DATE_CREATION) 
VALUES (2, 'Martin', 'Sophie', NULL, 'sophie.martin@email.com', '0698765432', SYSDATE);

INSERT INTO CLIENTS (ID_CLIENT, NOM, PRENOM, RAISON_SOCIALE, EMAIL, TELEPHONE, DATE_CREATION) 
VALUES (3, 'Bernard', 'Pierre', NULL, 'pierre.bernard@email.com', '0687654321', SYSDATE);

-- Clients entreprises
INSERT INTO CLIENTS (ID_CLIENT, NOM, PRENOM, RAISON_SOCIALE, EMAIL, TELEPHONE, DATE_CREATION) 
VALUES (4, 'TechCorp', NULL, 'TechCorp SARL', 'contact@techcorp.com', '0176543210', SYSDATE);

INSERT INTO CLIENTS (ID_CLIENT, NOM, PRENOM, RAISON_SOCIALE, EMAIL, TELEPHONE, DATE_CREATION) 
VALUES (5, 'Boulangerie Moderne', NULL, 'Boulangerie Moderne SAS', 'info@boulangerie-moderne.fr', '0165432109', SYSDATE);

COMMIT;