INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (1, 1, SYSDATE-10, 2500.00, 'CREDIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (2, 1, SYSDATE-8, -150.50, 'DEBIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (3, 1, SYSDATE-5, -80.00, 'DEBIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (4, 1, SYSDATE-3, -45.00, 'DEBIT');


INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (5, 2, SYSDATE-7, 500.00, 'CREDIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (6, 2, SYSDATE-2, 12.50, 'CREDIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (7, 3, SYSDATE-9, 1800.00, 'CREDIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (8, 3, SYSDATE-6, -650.00, 'DEBIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (9, 3, SYSDATE-4, -120.00, 'DEBIT');


INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (10, 4, SYSDATE-8, 3200.00, 'CREDIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (11, 4, SYSDATE-5, -200.00, 'DEBIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (12, 4, SYSDATE-2, -95.00, 'DEBIT');


INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (13, 5, SYSDATE-12, 25000.00, 'CREDIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (14, 5, SYSDATE-10, -8500.00, 'DEBIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (15, 5, SYSDATE-7, -1200.00, 'DEBIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (16, 5, SYSDATE-3, 15000.00, 'CREDIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (17, 6, SYSDATE-11, 3500.00, 'CREDIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (18, 6, SYSDATE-9, -1800.00, 'DEBIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (19, 6, SYSDATE-6, -450.00, 'DEBIT');

INSERT INTO MOUVEMENTS (ID_MOUVEMENT, ID_COMPTE, DATE_MOUVEMENT, MONTANT, TYPE_MOUVEMENT) 
VALUES (20, 6, SYSDATE-1, 4200.00, 'CREDIT');

COMMIT;